import Darwin
// SPDX-License-Identifier: Apache-2.0
import Foundation

enum PMKResourceError: Error, CustomStringConvertible {
    case missing(String)

    var description: String {
        switch self {
        case .missing(let message):
            return "PMK_RESOURCE: \(message)"
        }
    }
}

@_cdecl("pmk_resource_locator_anchor")
public func pmkResourceLocatorAnchor() {}

private let pmkResourceBundleName = "libpmk_PMK.bundle"

func pmkLoadedLibraryURL() -> URL? {
    var info = Dl_info()
    let symbol = unsafeBitCast(pmkResourceLocatorAnchor as @convention(c) () -> Void, to: UnsafeRawPointer.self)
    guard dladdr(symbol, &info) != 0, let imageName = info.dli_fname else {
        return nil
    }
    return URL(fileURLWithPath: String(cString: imageName)).resolvingSymlinksInPath()
}

func pmkResourceURL(_ relativePath: String,
                    environment: [String: String] = ProcessInfo.processInfo.environment,
                    loadedLibraryURL: URL? = pmkLoadedLibraryURL()) throws -> URL {
    let manager = FileManager.default

    func directoryExists(_ url: URL) -> Bool {
        var isDirectory = ObjCBool(false)
        return manager.fileExists(atPath: url.path, isDirectory: &isDirectory) && isDirectory.boolValue
    }

    func resource(in bundleURL: URL, source: String) throws -> URL {
        guard directoryExists(bundleURL) else {
            throw PMKResourceError.missing("\(source) path does not exist or is not a directory: \(bundleURL.path)")
        }
        let url = bundleURL.appendingPathComponent(relativePath)
        guard manager.fileExists(atPath: url.path) else {
            throw PMKResourceError.missing("\(source) is missing \(relativePath): \(url.path)")
        }
        return url
    }

    if let raw = environment["PMK_RESOURCE_BUNDLE"] {
        guard !raw.isEmpty else {
            throw PMKResourceError.missing("PMK_RESOURCE_BUNDLE is set to an empty path")
        }
        let url = URL(fileURLWithPath: raw).resolvingSymlinksInPath()
        guard directoryExists(url) else {
            throw PMKResourceError.missing("PMK_RESOURCE_BUNDLE path does not exist or is not a directory: \(raw)")
        }
        return try resource(in: url, source: "PMK_RESOURCE_BUNDLE")
    }

    var checked: [String] = []
    if let loadedLibraryURL {
        let url = loadedLibraryURL.deletingLastPathComponent().appendingPathComponent(pmkResourceBundleName)
        checked.append("next to libpmk.dylib: \(url.path)")
        if directoryExists(url) {
            return try resource(in: url, source: "bundle next to libpmk.dylib")
        }
    } else {
        checked.append("next to libpmk.dylib: <unavailable>")
    }

    let mainCandidate = Bundle.main.bundleURL.appendingPathComponent(pmkResourceBundleName)
    checked.append("next to main executable: \(mainCandidate.path)")
    var swiftPMBuildCandidate: URL?
    if let loadedLibraryURL {
        var directory = loadedLibraryURL.deletingLastPathComponent()
        while directory.path != "/" {
            if directory.path.contains("/.build/") {
                let candidate = directory.appendingPathComponent(pmkResourceBundleName)
                if Bundle(path: candidate.path) != nil {
                    swiftPMBuildCandidate = candidate
                    break
                }
            }
            let parent = directory.deletingLastPathComponent()
            if parent.path == directory.path { break }
            directory = parent
        }
    }
    if let swiftPMBuildCandidate {
        checked.append("SwiftPM build fallback: \(swiftPMBuildCandidate.path)")
    }

    // Bundle.module traps instead of throwing. Invoke it only after proving one
    // of the two locations generated by SwiftPM is a loadable bundle.
    if Bundle(path: mainCandidate.path) != nil || swiftPMBuildCandidate != nil {
        let module = Bundle.module
        guard let base = module.resourceURL else {
            throw PMKResourceError.missing("Bundle.module resource URL unavailable after validating \(mainCandidate.path)")
        }
        let url = base.appendingPathComponent(relativePath)
        guard manager.fileExists(atPath: url.path) else {
            throw PMKResourceError.missing("Bundle.module is missing \(relativePath): \(url.path)")
        }
        return url
    }

    throw PMKResourceError.missing(
        "could not locate \(pmkResourceBundleName) for \(relativePath); "
        + "PMK_RESOURCE_BUNDLE is unset; checked \(checked.joined(separator: "; "))"
    )
}
